openapi: 3.0.1
info:
  title: Factories Api
  description: Documentation of factories Api
  version: '0.1'
servers:
  - url: 'http://localhost:5000'
paths:
  /api/factories/id:
    get:
      description: Get a factory by id
      parameters:        
        - name: id          
          in: path           
          description: Id of the factory          
          required: true       
          schema:             
            $ref: '#/components/schemas/factoryId'
      responses:
        '200':
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/factoryItem'
        '400':
          description: Bad request
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
    delete:
      description: Delete factory by id
      parameters:        
        - name: id          
          in: path           
          description: Id of the factory          
          required: true       
          schema:             
            $ref: '#/components/schemas/factoryId'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad request
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '404':
          description: Not Found
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
  /api/factories:
    get:
        description: Get all the factories
        responses:
          '200':
            description: OK
            content:
              application/json; charset=utf-8:
                schema:
                  $ref: '#/components/schemas/factories'
          '400':
            description: Bad request
            content:
              application/json; charset=utf-8:
                schema:
                  $ref: '#/components/schemas/errorModelList'
          '401':
            description: Unauthorized
            content:
              application/json; charset=utf-8:
                schema:
                  $ref: '#/components/schemas/errorModelList'
          '500':
            description: Internal Server Error
            content:
              application/json; charset=utf-8:
                schema:
                  $ref: '#/components/schemas/errorModelList'
    put: 
      description: Make changes in a factory
      responses:
        '200':
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/factoryItem'
        '400':
          description: Bad request
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
    post:
      description: Post a new factory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/factoryItem'
        required: true
      responses:
        '201':
          description: Created
          content:
            text/plain; charset=utf-8:
              schema:
                $ref: '#/components/schemas/factoryItem'
        '400':
          description: Bad request
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
components:
  schemas:
    factoryId:
      title: Factory id
      description:  This is Id of the factory
      type: string
      example: '60167ca9d2f4825fa4aea4d8'
    factories:
      title: Factories
      description: Array of factories
      type: array
      items:
        $ref: '#/components/schemas/factoryItem'
    factoryItem:
      title: Factory item
      description: Object for factory
      type: object
      properties:
        name:
          description: Name of the factory
          type: string
          example: ABC
        director:
          description: Name of the factory director
          type: string
          example: Anna
        employers:
          description: Array of the factory employers
          type: array
          example: ['Elya', 'Anna']
        product:
          description: Array of the factory product
          type: array
          example: ['TV', 'PC', 'Printer']
      required:
        - name
        - director
        - employers
        - product
    errorModelList:
      title: List Error Model
      description: Common defintion for a list of errors. To be used as body in combination with the HTTP status code.
      type: object
      properties:
        errors:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/errorModel'
    errorModel:
      title: Error Model
      description: Common defintion of an error. To be used as body in combination with the HTTP status code.
      type: object
      properties:
        code:
          type: string
        property:
          type: string
        message:
          type: string